config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             only: %w[sessions registrations],
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }

  root 'groups#index'
  resources :groups, only: [:index, :new, :create] do
    collection do
      post :search
    end
    member do
      post :join
      post :remove_member
      post :respond_join_request
    end
    resources :posts do
      resources :comments
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, optional: false, class_name: 'User'
  has_many :members, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  enum access: Groups::Access::VALID_ACCESSES, _prefix: true

  def member_exist?(user: nil)
    return false if user.blank?

    members.where(user_id: user.id).exists?
  end

  def get_member(user: nil)
    return false if user.blank?

    members.where(user_id: user.id).first
  end

  def owner_is?(user: nil)
    return false if user.nil?

    owner.id == user.id
  end

  def owner_or_valid_member?(user: nil)
    return false if user.nil?

    owner_is?(user: user) || members.where(user_id: user.id, status: [Members::Status::ACCEPTED, Members::Status::OWNER]).first
  end
end

app/models/groups/access.rb
module Groups
  class Access
    OPEN = 'OPEN'
    PRIVATE = 'PRIVATE'

    VALID_ACCESSES = [
      OPEN,
      PRIVATE
    ].freeze
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :active_link
  before_action :set_group, only: [:join, :remove_member, :respond_join_request]

  def index
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      @member = @group.members.find_or_initialize_by(user_id: current_user.id)
      @member.status = Members::Status::OWNER
      @member.save
      NewGroupStreamJob.perform_later(@group.id, current_user.id)

      render turbo_stream: [
        turbo_stream.update('turbo_messages', render_to_string(Shared::TurboMessageComponent.new(notice: "Group created successfully"))),
        turbo_stream.update('groups_form_model', '')
      ]
    else
      render turbo_stream: turbo_stream.replace(@group, render_to_string(Groups::FormComponent.new(group: @group)))
    end
  end

  def search
    @groups = params[:type] == "all" ? Group.all : current_user.groups
    @groups = @groups.includes(:owner, :members)
    @groups = @groups.order(updated_at: :desc)
  end

  def join
    if @group.owner.id != current_user.id
      @member = @group.members.find_or_initialize_by(user_id: current_user.id)
      @member.status = @group.access == Groups::Access::PRIVATE ? Members::Status::PENDING : Members::Status::ACCEPTED if @member.new_record?
      @member.save!
      if @group.access == Groups::Access::PRIVATE
        Turbo::StreamsChannel.broadcast_prepend_to "group_#{@group.id}_pending_members_stream", html: render_to_string(Posts::PendingListItemComponent.new(group: @group, member: @member)), target: "group_#{@group.id}_pending_members"
      end
    end
  end

  def remove_member
    if @group.owner_is?(user: current_user)
      @member = @group.members.find_by(id: params[:member_id])
      @member.destroy
      RemoveMemberStreamJob.perform_later(@group, "joined_group_#{@group.id}_member_#{@member.id}")
      render turbo_stream: turbo_stream.remove("joined_group_#{@group.id}_member_#{@member.id}")
    end
  end

  def respond_join_request
    @member = @group.members.find_by(id: params[:member_id])
    @member.update!(status: params[:status])
    if params[:status] == Members::Status::ACCEPTED
      Turbo::StreamsChannel.broadcast_prepend_to "group_#{@group.id}_joined_members_stream", html: render_to_string(Posts::MemeberListItemComponent.new(group: @group, member: @member)), target: "group_#{@group.id}_joined_members"
    end
    Turbo::StreamsChannel.broadcast_remove_to "group_#{@group.id}_pending_members_stream", html: render_to_string(Posts::PendingListItemComponent.new(group: @group, member: @member)), target: "pending_group_#{@group.id}_member_#{@member.id}"
  end

  private

  def active_link
    set_header_active_link(Header::LINK_GROUP)
  end

  def group_params
    params.require(:group).permit(:id, :name, :access)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/views/groups/index.html.erb
<%= content_for :modal do %>
  <%= turbo_frame_tag "groups_form_model" do %>
  <% end %>
<% end %>
<div class="flex justify-between">
  <div></div>
  <%= link_to "Create a new group", new_group_path, data: { controller: "turbo-request", action: "click->turbo-request#click" }, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5" %>
</div>
<div class="groups-list-search-container mt-2 mb-2">
  <%= render Groups::ListSearchComponent.new %>
</div>
<div class="groups-list-items-container mt-2 mb-2">
  <%= turbo_stream_from "groups_list_items_stream" %>
  <%= turbo_frame_tag "groups_list_items" %>
</div>

app/views/groups/join.turbo_stream.erb
<%= turbo_stream.update @group, (render Groups::ListItemComponent.new(group: @group, user: current_user)) %>

app/views/groups/new.turbo_stream.erb
<%= turbo_stream.update "groups_form_model" do %>
  <%= render Groups::FormModalComponent.new(title: "Create Group") do %>
    <%= render Groups::FormComponent.new(group: @group) %>
  <% end %>
<% end %>

app/views/groups/search.turbo_stream.erb
<%= turbo_stream.update "groups_list_items", (render Groups::ListComponent.new(groups: @groups)) %>